version: '3.8'

services:
  # 1. The Database (MongoDB)
  db:
    image: mongo:6.0
    restart: always
    volumes:
      - db_data:/data/db
    networks:
      - app-network

  # 2. The Web Application (Built from your code)
  web:
    build: ./app
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    volumes:
      - upload_data:/app/uploads
    networks:
      - app-network

  # 3. Reverse Proxy Container (Nginx Proxy Manager)
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxy_data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  # 4. Monitoring: Prometheus
  prometheus:
    image: prom/prometheus
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  # 5. Monitoring: Grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network
    environment:
      - GF_SERVER_ROOT_URL=https://final-deployment.online
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # 6. Node Exporter (Host metrics)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - app-network

  # 7. cAdvisor (Container metrics)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app-network

volumes:
  db_data:
  upload_data:
  proxy_data:
  letsencrypt:
  grafana_data:

networks:
  app-network:
    driver: bridge
